FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r /app/requirements.txt

COPY api /app/api
COPY app_config.py /app/app_config.py
COPY services /app/services
COPY ingest /app/ingest

EXPOSE 8001

CMD ["python", "-m", "api"]

